export const NOTEPADS = {
  LOAD: "NOTEPAD_LOAD",
  LOAD_SUCCESS: "NOTEPAD_LOAD_SUCCESS",
  LOAD_ERROR: "NOTEPAD_LOAD_ERROR",

  CREATING: "NOTEPAD_CREATE",
  CREATE_SUCCESS: "NOTEPAD_CREATE_SUCCESS",
  CREATE_ERROR: "NOTEPAD_CREATE_ERROR",
};
