export const CALORIES = {
  LOAD: "CALORIES_LOADING",
  LOAD_SUCCESS: "CALORIES_LOAD_SUCCESS",
  LOAD_ERROR: "CALORIES_LOAD_ERROR",

  CREATE: "CALORIES_CREATING",
  CREATE_SUCCESS: "CALORIES_CREATE_SUCCESS",
  CREATE_ERROR: "CALORIES_CREATE_ERROR",
};
