export const CALORIES_LOADING = 'CALORIES_LOADING';
export const CALORIES_LOAD_SUCCESS = 'CALORIES_LOAD_SUCCESS';
export const CALORIES_LOAD_ERROR = 'CALORIES_LOAD_ERROR';
export const CALORIES_CREATING = 'CALORIES_CREATING';
export const CALORIES_CREATE_SUCCESS = 'CALORIES_CREATE_SUCCESS';
export const CALORIES_CREATE_ERROR = 'CALORIES_CREATE_ERROR';
export const CALORY_DELETE = 'CALORY_DELETE';