export const AUTH = {
  LOGIN_START: "LOG_IN_START",
  LOGIN_SUCCESS: "LOG_IN_SUCCESS",
  LOGIN_FAILURE: "LOG_IN_FAILURE",
  SIGNUP_START: "REGISTER_START",
  SIGNUP_SUCCESS: "REGISTER_SUCCESS",
  SIGNUP_FAILURE: "REGISTER_FAILURE",
  LOG_OUT: "LOG_OUT",
};
